# Generated by Django 5.1.6 on 2025-03-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='owner',
        ),
    ]
