# Generated by Django 5.1.6 on 2025-03-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='currency',
            field=models.CharField(choices=[('MKD', 'ден.'), ('EUR', 'е')], default='MKD', max_length=3),
        ),
    ]
