# Generated by Django 5.1.6 on 2025-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ad_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('AVTOMOBILI', 'Автомобили'), ('MOBILNI', 'Мобилни телефони'), ('ELEKTRONIKA', 'Електроника'), ('DOM', 'Дом и градина'), ('MODA', 'Мода'), ('USLUGI', 'Услуги'), ('DRUGO', 'Друго')], default='DRUGO', max_length=100),
        ),
    ]
